# Generated by Django 5.1.1 on 2024-10-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifocus_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
